get http://localhost:3001/api/playlist/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXJuYW1lIiwibmFtZSI6Im5ld05hbWUiLCJpZCI6IjYwZWU1YjUwNzNlZWEyMmFjMDE1NjM2ZiIsImlhdCI6MTYyNjM1ODcxOH0.dMwY0rShQJ3zK24OdquQUsuGNJPRysw0FqfpXHEQah0